version: '3.4'

services:
  djakashcontent:
    image: djakashcontent
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app